name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: composer update --lock

    - name: Run Comparability Checker
      run: ./vendor/bin/phpcs -p --ignore=*/vendor/* . --standard=PHPCompatibility --runtime-set testVersion 7.4
